In [ ]:
import pandas as pd

In [37]:
american = pd.read_csv('cuisine_data/american.csv' )
british = pd.read_csv('cuisine_data/british.csv' )
caribbean = pd.read_csv('cuisine_data/caribbean.csv')
chinese = pd.read_csv('cuisine_data/chinese.csv' )
french = pd.read_csv('cuisine_data/french.csv' )
greek = pd.read_csv('cuisine_data/greek.csv')
indian = pd.read_csv('cuisine_data/indian.csv' )
italian = pd.read_csv('cuisine_data/italian.csv' )
japanese = pd.read_csv('cuisine_data/japanese.csv' )
mediterranean = pd.read_csv('cuisine_data/mediterranean.csv' )
mexican = pd.read_csv('cuisine_data/mexican.csv' )
moroccan = pd.read_csv('cuisine_data/moroccan.csv' )
spanish = pd.read_csv('cuisine_data/spanish.csv' )
thai = pd.read_csv('cuisine_data/thai.csv' )
turkish = pd.read_csv('cuisine_data/turkish.csv' )
vietnamese = pd.read_csv('cuisine_data/vietnamese.csv' )

In [38]:
cuisines = [american, british, caribbean, chinese, french, greek, indian, italian, japanese, mediterranean, mexican, moroccan, spanish, thai, turkish, vietnamese]

cuisines_df = pd.concat(cuisines)

cuisines_df

,Unnamed: 0,name,ingredients,cuisine
0,0,Buffalo chicken,1 ½kg chicken thighs and drumsticks 180g sea s...,american-recipes
1,1,Texas BBQ medley,"1 large chicken 5 beef short ribs (about 3kg),...",american-recipes
2,2,Pecan pie with maple cream,"150g unsalted butter , softened 80g golden cas...",american-recipes
3,3,BBQ chicken platter,"1 whole chicken , jointed, or 8 bone-in chicke...",american-recipes
4,4,Truffled mac 'n' cheese,500g macaroni 1l whole milk 2 bay leaves 60g b...,american-recipes
...,...,...,...,...
25,19,Crunchy prawn noodle salad,"100g rice noodle 100g sugar snap pea , shredde...",vietnamese-recipes
26,20,Noodle bowl salad,½ x 250g pack medium rice noodles 200g sugar ...,vietnamese-recipes
27,21,Asian prawn & pineapple salad,1 small pineapple or 350g pineapple chunks 140...,vietnamese-recipes
28,22,"Tangy carrot, red cabbage & onion salad","4 carrots , cut into thin sticks or grated ½ r...",vietnamese-recipes
29,23,Asian chicken salad,"1 boneless, skinless chicken breast 1 tbsp fis...",vietnamese-recipes

In [43]:
cuisines_df.drop(columns = 'Unnamed: 0', inplace = True)

In [45]:
cuisines_df.to_csv('goodfood.csv')

In [62]:
cuisines_df = pd.read_csv('goodfood.csv', index_col = 0)
cuisines_df

,name,ingredients,cuisine
0,Buffalo chicken,1 ½kg chicken thighs and drumsticks 180g sea s...,american-recipes
1,Texas BBQ medley,"1 large chicken 5 beef short ribs (about 3kg),...",american-recipes
2,Pecan pie with maple cream,"150g unsalted butter , softened 80g golden cas...",american-recipes
3,BBQ chicken platter,"1 whole chicken , jointed, or 8 bone-in chicke...",american-recipes
4,Truffled mac 'n' cheese,500g macaroni 1l whole milk 2 bay leaves 60g b...,american-recipes
...,...,...,...
25,Crunchy prawn noodle salad,"100g rice noodle 100g sugar snap pea , shredde...",vietnamese-recipes
26,Noodle bowl salad,½ x 250g pack medium rice noodles 200g sugar ...,vietnamese-recipes
27,Asian prawn & pineapple salad,1 small pineapple or 350g pineapple chunks 140...,vietnamese-recipes
28,"Tangy carrot, red cabbage & onion salad","4 carrots , cut into thin sticks or grated ½ r...",vietnamese-recipes
29,Asian chicken salad,"1 boneless, skinless chicken breast 1 tbsp fis...",vietnamese-recipes

In [63]:
cuisines_dict_map = {'american-recipes': 1, 'british-recipes': 2, 'caribbean-recipes': 3, 'chinese-recipes': 4, 'french-recipes': 5, 'greek-recipes': 6, 'indian-recipes': 7, 'italian-recipes': 8, 'japanese-recipes': 9, 'mediterranean-recipes': 10, 'mexican-recipes': 11, 'moroccan-recipes': 12, 'spanish-recipes': 13, 'thai-recipes': 14, 'turkish-recipes': 15, 'vietnamese-recipes': 16}

In [64]:
cuisines_df['cuisine'] = cuisines_df['cuisine'].replace(cuisines_dict_map)
cuisines_df

,name,ingredients,cuisine
0,Buffalo chicken,1 ½kg chicken thighs and drumsticks 180g sea s...,1
1,Texas BBQ medley,"1 large chicken 5 beef short ribs (about 3kg),...",1
2,Pecan pie with maple cream,"150g unsalted butter , softened 80g golden cas...",1
3,BBQ chicken platter,"1 whole chicken , jointed, or 8 bone-in chicke...",1
4,Truffled mac 'n' cheese,500g macaroni 1l whole milk 2 bay leaves 60g b...,1
...,...,...,...
25,Crunchy prawn noodle salad,"100g rice noodle 100g sugar snap pea , shredde...",16
26,Noodle bowl salad,½ x 250g pack medium rice noodles 200g sugar ...,16
27,Asian prawn & pineapple salad,1 small pineapple or 350g pineapple chunks 140...,16
28,"Tangy carrot, red cabbage & onion salad","4 carrots , cut into thin sticks or grated ½ r...",16
29,Asian chicken salad,"1 boneless, skinless chicken breast 1 tbsp fis...",16

In [68]:
cuisines_df['Ingredients'] = cuisines_df['ingredients']
cuisines_df['Cuisine'] = cuisines_df['cuisine']
cuisines_df.drop(columns = ['name', 'ingredients', 'cuisine'], inplace = True)

In [69]:
cuisines_df

                                          Ingredients  Cuisine
0   1 ½kg chicken thighs and drumsticks 180g sea s...        1
1   1 large chicken 5 beef short ribs (about 3kg),...        1
2   150g unsalted butter , softened 80g golden cas...        1
3   1 whole chicken , jointed, or 8 bone-in chicke...        1
4   500g macaroni 1l whole milk 2 bay leaves 60g b...        1
..                                                ...      ...
25  100g rice noodle 100g sugar snap pea , shredde...       16
26  ½ x 250g pack medium  rice noodles 200g sugar ...       16
27  1 small pineapple or 350g pineapple chunks 140...       16
28  4 carrots , cut into thin sticks or grated ½ r...       16
29  1 boneless, skinless chicken breast 1 tbsp fis...       16

[729 rows x 2 columns]

In [70]:
cuisines_df.to_csv('final_goodfood.csv')

In [ ]:
def concat_overall_dataframe():
    #takes in each individual bbc cuisine csv and concats them into one overall dataframe

    american = pd.read_csv('cuisine_data/american.csv' )
    british = pd.read_csv('cuisine_data/british.csv' )
    caribbean = pd.read_csv('cuisine_data/caribbean.csv')
    chinese = pd.read_csv('cuisine_data/chinese.csv' )
    french = pd.read_csv('cuisine_data/french.csv' )
    greek = pd.read_csv('cuisine_data/greek.csv')
    indian = pd.read_csv('cuisine_data/indian.csv' )
    italian = pd.read_csv('cuisine_data/italian.csv' )
    japanese = pd.read_csv('cuisine_data/japanese.csv' )
    mediterranean = pd.read_csv('cuisine_data/mediterranean.csv' )
    mexican = pd.read_csv('cuisine_data/mexican.csv' )
    moroccan = pd.read_csv('cuisine_data/moroccan.csv' )
    spanish = pd.read_csv('cuisine_data/spanish.csv' )
    thai = pd.read_csv('cuisine_data/thai.csv' )
    turkish = pd.read_csv('cuisine_data/turkish.csv' )
    vietnamese = pd.read_csv('cuisine_data/vietnamese.csv' )

    cuisines = [american, british, caribbean, chinese, french, greek, indian, italian, japanese, mediterranean, mexican, moroccan, spanish, thai, turkish, vietnamese]

    cuisines_df = pd.concat(cuisines)
    
    cuisines_dict_map = {'american-recipes': 1, 'british-recipes': 2, 'caribbean-recipes': 3, 'chinese-recipes': 4, 'french-recipes': 5, 'greek-recipes': 6, 'indian-recipes': 7, 'italian-recipes': 8, 'japanese-recipes': 9, 'mediterranean-recipes': 10, 'mexican-recipes': 11, 'moroccan-recipes': 12, 'spanish-recipes': 13, 'thai-recipes': 14, 'turkish-recipes': 15, 'vietnamese-recipes': 16}


    cuisines_df['cuisine'] = cuisines_df['cuisine'].replace(cuisines_dict_map)


    cuisines_df.to_csv('final_goodfood.csv')

# concat_overall_dataframe()